### ISSUE TITLE
Required plugins

### ISSUE THREAD

**Issue by KrzysztofMadejski** [bezbeli/faktograf#3]
Are they really all required?
- [Google Analytics by MonsterInsights](https://www.monsterinsights.com/)
- [Monarch](https://www.elegantthemes.com/plugins/monarch/)
- [Yoast SEO](https://yoast.com/)
- [Wodrfence](https://www.wordfence.com/)
- [WP-Polls](https://wordpress.org/plugins/wp-polls/) - I guess really required plugin is the this - the polls. Still, were are they used?

**Comment by bezbeli** [comment]
You are right, they are not really required, only WP-Polls is actually required, I'll change this in readme.md
