### ISSUE TITLE
Advanced Custom Fields

### ISSUE THREAD

**Issue by KrzysztofMadejski** [bezbeli/faktograf#4]
I see that [you are using](http://faktograf.hr/site/wp-admin/edit.php?post_type=acf-field-group) ACF, but I don't see it in the list of plugins. I don't get it how it works.. Did it got incorporated into Wordpress?

**Comment by bezbeli** [comment]
ACF is incorporated inside the theme

**Comment by KrzysztofMadejski** [comment]
ok, thanks!
